// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerEnhancer) DeepCopyInto(out *SchedulerEnhancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerEnhancer.
func (in *SchedulerEnhancer) DeepCopy() *SchedulerEnhancer {
	if in == nil {
		return nil
	}
	out := new(SchedulerEnhancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchedulerEnhancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerEnhancerList) DeepCopyInto(out *SchedulerEnhancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SchedulerEnhancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerEnhancerList.
func (in *SchedulerEnhancerList) DeepCopy() *SchedulerEnhancerList {
	if in == nil {
		return nil
	}
	out := new(SchedulerEnhancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SchedulerEnhancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerEnhancerSpec) DeepCopyInto(out *SchedulerEnhancerSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerEnhancerSpec.
func (in *SchedulerEnhancerSpec) DeepCopy() *SchedulerEnhancerSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulerEnhancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerEnhancerStatus) DeepCopyInto(out *SchedulerEnhancerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerEnhancerStatus.
func (in *SchedulerEnhancerStatus) DeepCopy() *SchedulerEnhancerStatus {
	if in == nil {
		return nil
	}
	out := new(SchedulerEnhancerStatus)
	in.DeepCopyInto(out)
	return out
}
