apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedulerenhancer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: schedulerenhancer
  template:
    metadata:
      labels:
        name: schedulerenhancer
    spec:
      serviceAccountName: schedulerenhancer
      containers:
        - name: schedulerenhancer
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - schedulerenhancer
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "schedulerenhancer"
