kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: schedulerenhancer
subjects:
- kind: ServiceAccount
  name: schedulerenhancer
roleRef:
  kind: Role
  name: schedulerenhancer
  apiGroup: rbac.authorization.k8s.io
